### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by buzmax** [afterpay/sdk-android#139]
could you make new release pls with these changes, we have a blocker
https://github.com/afterpay/sdk-android/pull/136

**Comment by buzmax** [comment]
https://github.com/afterpay/sdk-android/pull/138
and this also

**Comment by ScottAntonacAP** [comment]
Hi @buzmax,

Version 3.0.0 of the SDK has been released, which includes the requested changes. Please note that it also contains breaking changes as indicated on the [release page](https://github.com/afterpay/sdk-android/releases/tag/v3.0.0).
