### ISSUE TITLE
Bug: Documents can be written incorrectly

### ISSUE THREAD

**Issue by billdizl** [afterpay/sdk-android#200]
I trembled with laughter as even a large company's documents could be written incorrectly,Owl and scream~~~
https://afterpay.github.io/sdk-android/

**Comment by ScottAntonacAP** [comment]
Hi @billdizi,

Thank you for taking the time to provide feedback.

Please provide a description of the issue. Which part of the documents are "written incorrectly"?

Thank you.

**Comment by billdizl** [comment]
see setp 6B,ios not have this problem,i find demo & documents have, i want to know have you verified it after writing it?

**Comment by billdizl** [comment]
<img width="941" alt="image" src="https://github.com/afterpay/sdk-android/assets/30317994/a1481ea2-b23e-4fb2-b648-18b8241b3fb3">
<img width="1392" alt="image" src="https://github.com/afterpay/sdk-android/assets/30317994/a8ceddf7-4c33-45ae-94fe-f4824ba75dd9">

**Comment by billdizl** [comment]
Isn't it very funny?

**Comment by billdizl** [comment]
are u sure changed documents?https://afterpay.github.io/sdk-android/

**Comment by billdizl** [comment]
i see. u only change demo
